file:
  bucket-name: test
  oss:
#    对象存储服务的URL
    endpoint: http://127.0.0.1:9000
#    自定义域名
    customDomain: http://localhost:9000
#    路径样式访问
    pathStyleAccess: false
#    应用ID
    appId: test_appId
#    区域
    region: test_region
#    Access key就像用户ID，可以唯一标识你的账户
    access-key: aCUjNqdJfFdgi20ZHkKH
#    Secret key是你账户的密码
    secret-key: quFIlrQKjMJ0LiTAN5JACwsfmWy8gCZHfiMEaQqH
#    最大线程数，默认： 100
    maxConnections: 100

    info: true
    enable: true
  local:
    enable: true
    basePath: /Users/anuouan/Desktop/oss

#spring:
#  aop:
#    auto: true
#file:
#  bucket-name: test
#
#  #  文件大小限制
#  oss:
#    enable: true
#    pathStyleAccess: false
#    #  自定义域名
#    #  customDomain:
#    #  对象存储服务的URL
#    endpoint: http://localhost:9000
#    access-key: aCUjNqdJfFdgi20ZHkKH
#    secret-key: quFIlrQKjMJ0LiTAN5JACwsfmWy8gCZHfiMEaQqH

